### ISSUE TITLE
libplatform/platform_win32.cpp:27:21: fatal error: windows.h: No such file or directory

### ISSUE THREAD

**Issue by sebma** [svnpenn/mp4v2#184] opened 2016-06-07 00:00 UTC
Hi,

I'm using Ubuntu Linux but for some reason I see the following when building : 
```
libtool: compile:  g++ -DHAVE_CONFIG_H -I./include -I./include -I. -I. -Wall -Wformat -g -O2 -fvisibility=hidden -c libplatform/platform_win32.cpp  -fPIC -DPIC -o libplatform/.libs/platform_win32.o
libplatform/platform_win32.cpp:27:21: fatal error: windows.h: No such file or directory
 #include <windows.h>
                     ^
compilation terminated.
GNUmakefile:1315: recipe for target 'libplatform/platform_win32.lo' failed
make: *** [libplatform/platform_win32.lo] Error 1
$ echo $?
2
```

Can you help ?

**Comment by svnpenn** [comment] 2016-06-07 00:04
I am closing this, because you are vague. You need to indicate if you are building FOR Windows or FOR Linux. If you can clarify I will reopen

**Comment by sebma** [comment] 2016-06-07 00:06
I'm building on Linux for Linux :)

**Comment by svnpenn** [comment] 2016-06-07 00:11
`windows.h` is a Windows file, so you wont have it and wont need it unless you are building for Windows. I will have to check if it is being included when it shouldnt be. I will tell you though, I build for Windows so this is low priority

**Comment by sebma** [comment] 2016-06-07 00:18
I see in your GNUmakefile.am references to `libplatform/platform_win32.cpp` and `libplatform/platform_win32.h` in `libmp4v2_la_SOURCES` variable.

Can you move them into the `if ADD_PLATFORM_WIN32` block ?

**Comment by svnpenn** [comment] 2016-06-07 00:23
This was caused by

https://github.com/svnpenn/mp4v2/commit/fdcfae0255e2357fd0bfbec7bc43261d2e4a3978

I will see about fixing it

**Comment by sebma** [comment] 2016-06-07 00:30
Thank you.

In the meantime, I updated my local `GNUmakefile.am` and the build was successful :)

**Comment by svnpenn** [comment] 2016-06-07 01:41
@sebma check new commit

**Closed** 2016-06-07 01:40 UTC

**Comment by sebma** [comment] 2016-06-07 01:53
It seems your commit is fine, the buid is successful :)
